#!/usr/bin/env ruby

require_relative "game"
require_relative "display"
require_relative "board"
require_relative "message"
require_relative "ship"
require_relative "coordinate_validator"

message = Message.new
dimension = 25
board = Board.new(dimension)
validator = CoordinateValidator.new(board)
display = Display.new(message, validator)
game = Game.new(display, board)
ship_mode = 2
player_mode = 5
game.play(ship_mode, player_mode)
